<?php
/**
 * MUSeo.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Nov 25 15:03:25 CET 2012.
 */

/**
 * Generic item list content plugin implementation class
 */
class MUSeo_ContentType_ItemList extends MUSeo_ContentType_Base_ItemList
{
    // feel free to extend the content type here
}

function MUSeo_Api_ContentTypes_itemlist($args)
{
    return new MUSeo_Api_ContentTypes_itemListPlugin();
}
