<?php
/**
 * MUSeo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de) at Tue Jan 20 13:47:40 CET 2015.
 */

/**
 * Version information implementation class.
 */
class MUSeo_Version extends MUSeo_Base_Version
{
    /**
     * Retrieves meta data information for this application.
     *
     * @return array List of meta data.
     */
    public function getMetaData()
    {
        $meta = parent::getMetaData();

        // override description
        $meta['displayname'] = $this->__('MUSeo');
        $meta['description'] = $this->__('MUSeo - a module to handle SEO better.');

        // allow usage in 1.4
        $meta['core_max'] = '1.4.99'; // not ready for 1.5.x yet

        return $meta;
    }
}
