<?php
/**
 * MUSeo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * This is the HandleModules api helper class.
 */
class MUSeo_Api_Base_HandleModules extends Zikula_AbstractApi
{
    /**
     * Returns available handlemodules panel links.
     *
     * @return array Array of handlemodules links.
     */
    public function getLinks()
    {
        $links = array();


        $controllerHelper = new MUSeo_Util_Controller($this->serviceManager);
        $utilArgs = array('api' => 'handlemodules', 'action' => 'getLinks');
        $allowedObjectTypes = $controllerHelper->getObjectTypes('api', $utilArgs);

        $currentType = $this->request->query->filter('type', 'metatag', FILTER_SANITIZE_STRING);
        $currentLegacyType = $this->request->query->filter('lct', 'user', FILTER_SANITIZE_STRING);
        $permLevel = in_array('admin', array($currentType, $currentLegacyType)) ? ACCESS_ADMIN : ACCESS_READ;


        return $links;
    }
}
