<?php
/**
 * MUSeo.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Nov 25 15:03:25 CET 2012.
 */

/**
 * This handler class handles the page events of the Form called by the MUSeo_admin_edit() function.
 * It collects common functionality required by different object types.
 */
class MUSeo_Form_Handler_Admin_Edit extends MUSeo_Form_Handler_Admin_Base_Edit
{
    // feel free to extend the base handler class here
}
