<?php
/**
 * MUSeo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the mUSeo_metatag_edit() function.
 * It aims on the metatag object type.
 */
class MUSeo_Form_Handler_Metatag_Edit extends MUSeo_Form_Handler_Metatag_Base_Edit
{
    // feel free to extend the base handler class here
}
