<?php
/**
 * MUSeo.
 *
 * @copyright Michael ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael ueberschaer <konakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Nov 25 13:18:41 CET 2012.
 */

/**
 * Mailz api implementation class
 */
class MUSeo_Api_Mailz extends MUSeo_Api_Base_Mailz
{
    // feel free to extend the mailz api here
}
