<?php
/**
 * MUSeo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Installer base class.
 */
class MUSeo_Base_Installer extends Zikula_AbstractInstaller
{
    /**
     * Install the MUSeo application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        // Check if upload directories exist and if needed create them
        try {
            $controllerHelper = new MUSeo_Util_Controller($this->serviceManager);
            $controllerHelper->checkAndCreateAllUploadFolders();
        } catch (\Exception $e) {
            return LogUtil::registerError($e->getMessage());
        }
        // create all tables from according entity definitions
        try {
            DoctrineHelper::createSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                return LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            $returnMessage = $this->__f('An error was encountered while creating the tables for the %s extension.', array($this->name));
            if (!System::isDevelopmentMode()) {
                $returnMessage .= ' ' . $this->__('Please enable the development mode by editing the /config/config.php file in order to reveal the error details.');
            }
            return LogUtil::registerError($returnMessage);
        }
    
        // set up all our vars with initial values
        $this->setVar('modules', 'News');
        $this->setVar('controllers', 'main,view,display');
        $this->setVar('ignoreMetaDescriptionWarning', false);
        $this->setVar('ignorePermalink', false);
        $this->setVar('ignoreTour', false);
        $this->setVar('themeDescriptionFound', false);
        $this->setVar('themeHasDescription', false);
        $this->setVar('robotsIndex',  'index' );
        $this->setVar('robotsFollow',  'follow' );
        $this->setVar('disableAdvancedMeta', true);
        $this->setVar('alexaVerify', '');
        $this->setVar('googleVerify', '');
        $this->setVar('msVerify', '');
        $this->setVar('pinterestVerify', '');
        $this->setVar('yandexVerify', '');
        $this->setVar('enforceTrailingSlash', false);
        $this->setVar('cleanSlugs', true);
        $this->setVar('forceTransport', 'default');
        $this->setVar('cleanPermalinkGoogleSiteSearch', false);
        $this->setVar('cleanPermalinkGoogleCampaign', false);
        $this->setVar('cleanPermalinkExtraVars', '');
        $this->setVar('titleTest', 0);
        $this->setVar('forceRewriteTitle', false);
        $this->setVar('titleSeparator', 'sc-dash');
        $this->setVar('useMetaKeywords', false);
        $this->setVar('noodp', false);
        $this->setVar('noydir', false);
        $this->setVar('homeTitle', '%%sitename%% %%page%% %%sep%% %%sitedesc%%');
        $this->setVar('homeMetaDescription', '');
        $this->setVar('homeMetaKeywords', '');
        $this->setVar('searchTitle', '');
        $this->setVar('notFoundTitle', '');
        $this->setVar('facebookAdmins', '');
        $this->setVar('facebookApps', '');
        $this->setVar('facebookConnectKey', '');
        $this->setVar('openGraphEnabled', true);
        $this->setVar('facebookAdminApp', 0);
        $this->setVar('facebookSite', '');
        $this->setVar('openGraphFrontpageTitle', '');
        $this->setVar('openGraphFrontpageDescription', '');
        $this->setVar('openGraphFrontpageImage', '');
        $this->setVar('openGraphDefaultImage', '');
        $this->setVar('twitterEnabled', false);
        $this->setVar('twitterSiteUser', '');
        $this->setVar('twitterDefaultCardType', 'summary');
        $this->setVar('googlePlusEnabled', false);
        $this->setVar('googlePlusPublisherPage', '');
        $this->setVar('whatsAppEnabled', false);
    
        $categoryRegistryIdsPerEntity = array();
    
        // create the default data
        $this->createDefaultData($categoryRegistryIdsPerEntity);
    
        // register persistent event handlers
        $this->registerPersistentEventHandlers();
    
        // register hook subscriber bundles
        HookUtil::registerSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the MUSeo application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldVersion)
    {
    /*
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case '1.0.0':
                // do something
                // ...
                // update the database schema
                try {
                    DoctrineHelper::updateSchema($this->entityManager, $this->listEntityClasses());
                } catch (\Exception $e) {
                    if (System::isDevelopmentMode()) {
                        return LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
                    }
                    return LogUtil::registerError($this->__f('An error was encountered while updating tables for the %s extension.', array($this->getName())));
                }
        }
    */
    
        // update successful
        return true;
    }
    
    /**
     * Uninstall MUSeo.
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule($this->getName());
        if ($result === false) {
            return LogUtil::registerError($this->__f('An error was encountered while removing stored object workflows for the %s extension.', array($this->getName())));
        }
    
        try {
            DoctrineHelper::dropSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                return LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while dropping tables for the %s extension.', array($this->name)));
        }
    
        // unregister persistent event handlers
        EventUtil::unregisterPersistentModuleHandlers($this->name);
    
        // unregister hook subscriber bundles
        HookUtil::unregisterSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // remove all module vars
        $this->delVars();
    
        // remove all thumbnails
        $manager = $this->getServiceManager()->getService('systemplugin.imagine.manager');
        $manager->setModule($this->name);
        $manager->cleanupModuleThumbs();
    
        // remind user about upload folders not being deleted
        $uploadPath = FileUtil::getDataDirectory() . '/' . $this->name . '/';
        LogUtil::registerStatus($this->__f('The upload directories at [%s] can be removed manually.', $uploadPath));
    
        // uninstallation successful
        return true;
    }
    
    /**
     * Build array with all entity classes for MUSeo.
     *
     * @return array list of class names.
     */
    protected function listEntityClasses()
    {
        $classNames = array();
        $classNames[] = 'MUSeo_Entity_Metatag';
        $classNames[] = 'MUSeo_Entity_Extension';
    
        return $classNames;
    }
    
    /**
     * Create the default data for MUSeo.
     *
     * @param array $categoryRegistryIdsPerEntity List of category registry ids.
     *
     * @return void
     */
    protected function createDefaultData($categoryRegistryIdsPerEntity)
    {
        $entityClass = 'MUSeo_Entity_Metatag';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $entityClass = 'MUSeo_Entity_Extension';
        $this->entityManager->getRepository($entityClass)->truncateTable();
    }
    
    /**
     * Register persistent event handlers.
     * These are listeners for external events of the core and other modules.
     */
    protected function registerPersistentEventHandlers()
    {
        // core -> 
        EventUtil::registerPersistentModuleHandler('MUSeo', 'api.method_not_found', array('MUSeo_Listener_Core', 'apiMethodNotFound'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'core.preinit', array('MUSeo_Listener_Core', 'preInit'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'core.init', array('MUSeo_Listener_Core', 'init'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'core.postinit', array('MUSeo_Listener_Core', 'postInit'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'controller.method_not_found', array('MUSeo_Listener_Core', 'controllerMethodNotFound'));
    
        // front controller -> MUSeo_Listener_FrontController
        EventUtil::registerPersistentModuleHandler('MUSeo', 'frontcontroller.predispatch', array('MUSeo_Listener_FrontController', 'preDispatch'));
    
        // installer -> MUSeo_Listener_Installer
        EventUtil::registerPersistentModuleHandler('MUSeo', 'installer.module.installed', array('MUSeo_Listener_Installer', 'moduleInstalled'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'installer.module.upgraded', array('MUSeo_Listener_Installer', 'moduleUpgraded'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'installer.module.uninstalled', array('MUSeo_Listener_Installer', 'moduleUninstalled'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'installer.subscriberarea.uninstalled', array('MUSeo_Listener_Installer', 'subscriberAreaUninstalled'));
    
        // modules -> MUSeo_Listener_ModuleDispatch
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module_dispatch.postloadgeneric', array('MUSeo_Listener_ModuleDispatch', 'postLoadGeneric'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module_dispatch.preexecute', array('MUSeo_Listener_ModuleDispatch', 'preExecute'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module_dispatch.postexecute', array('MUSeo_Listener_ModuleDispatch', 'postExecute'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module_dispatch.custom_classname', array('MUSeo_Listener_ModuleDispatch', 'customClassname'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module_dispatch.service_links', array('MUSeo_Listener_ModuleDispatch', 'serviceLinks'));
    
        // mailer -> MUSeo_Listener_Mailer
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.mailer.api.sendmessage', array('MUSeo_Listener_Mailer', 'sendMessage'));
    
        // page -> MUSeo_Listener_Page
        EventUtil::registerPersistentModuleHandler('MUSeo', 'pageutil.addvar_filter', array('MUSeo_Listener_Page', 'pageutilAddvarFilter'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'system.outputfilter', array('MUSeo_Listener_Page', 'systemOutputfilter'));
    
        // errors -> MUSeo_Listener_Errors
        EventUtil::registerPersistentModuleHandler('MUSeo', 'setup.errorreporting', array('MUSeo_Listener_Errors', 'setupErrorReporting'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'systemerror', array('MUSeo_Listener_Errors', 'systemError'));
    
        // theme -> MUSeo_Listener_Theme
        EventUtil::registerPersistentModuleHandler('MUSeo', 'theme.preinit', array('MUSeo_Listener_Theme', 'preInit'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'theme.init', array('MUSeo_Listener_Theme', 'init'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'theme.load_config', array('MUSeo_Listener_Theme', 'loadConfig'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'theme.prefetch', array('MUSeo_Listener_Theme', 'preFetch'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'theme.postfetch', array('MUSeo_Listener_Theme', 'postFetch'));
    
        // view -> MUSeo_Listener_View
        EventUtil::registerPersistentModuleHandler('MUSeo', 'view.init', array('MUSeo_Listener_View', 'init'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'view.postfetch', array('MUSeo_Listener_View', 'postFetch'));
    
        // user login -> MUSeo_Listener_UserLogin
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.login.started', array('MUSeo_Listener_UserLogin', 'started'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.login.veto', array('MUSeo_Listener_UserLogin', 'veto'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.login.succeeded', array('MUSeo_Listener_UserLogin', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.login.failed', array('MUSeo_Listener_UserLogin', 'failed'));
    
        // user logout -> MUSeo_Listener_UserLogout
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.logout.succeeded', array('MUSeo_Listener_UserLogout', 'succeeded'));
    
        // user -> MUSeo_Listener_User
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.gettheme', array('MUSeo_Listener_User', 'getTheme'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.account.create', array('MUSeo_Listener_User', 'create'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.account.update', array('MUSeo_Listener_User', 'update'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.account.delete', array('MUSeo_Listener_User', 'delete'));
    
        // registration -> MUSeo_Listener_UserRegistration
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.registration.started', array('MUSeo_Listener_UserRegistration', 'started'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.registration.succeeded', array('MUSeo_Listener_UserRegistration', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.registration.failed', array('MUSeo_Listener_UserRegistration', 'failed'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.registration.create', array('MUSeo_Listener_UserRegistration', 'create'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.registration.update', array('MUSeo_Listener_UserRegistration', 'update'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.registration.delete', array('MUSeo_Listener_UserRegistration', 'delete'));
    
        // users module -> MUSeo_Listener_Users
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.config.updated', array('MUSeo_Listener_Users', 'configUpdated'));
    
        // group -> MUSeo_Listener_Group
        EventUtil::registerPersistentModuleHandler('MUSeo', 'group.create', array('MUSeo_Listener_Group', 'create'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'group.update', array('MUSeo_Listener_Group', 'update'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'group.delete', array('MUSeo_Listener_Group', 'delete'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'group.adduser', array('MUSeo_Listener_Group', 'addUser'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'group.removeuser', array('MUSeo_Listener_Group', 'removeUser'));
    
    }
}
