<?php
/**
 * MUSeo.
 *
 * @copyright Michael ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael ueberschaer <konakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Nov 18 21:06:00 CET 2012.
 */

/**
 * Utility implementation class for model helper methods.
 */
class MUSeo_Util_Model extends MUSeo_Util_Base_Model
{
    /**
	*
	 This method is for getting a repository for metatags
	*
	*/
    
    public static function getMetatagRepository() {
    
     $serviceManager = ServiceUtil::getManager();
     $entityManager = $serviceManager->getService('doctrine.entitymanager');
     $repository = $entityManager->getRepository('MUSeo_Entity_Metatag');
    
     return $repository;
    } 
    
        /**
	*
	 This method is for getting a repository for modules
	*
	*/
    
    public static function getModuleRepository() {
    
     $serviceManager = ServiceUtil::getManager();
     $entityManager = $serviceManager->getService('doctrine.entitymanager');
     $repository = $entityManager->getRepository('MUSeo_Entity_Module');
    
     return $repository;
    } 
}
