<?php
/**
 * MUSeo.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Nov 25 15:03:25 CET 2012.
 */

/**
 * Installer implementation class
 */
class MUSeo_Installer extends MUSeo_Base_Installer
{
    /**
     * Upgrade the MUSeo application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldversion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldversion)
    {
    
        // Upgrade dependent on old version number
        switch ($oldversion) {
            case '1.0.0':
                // nothing to do
            case '1.0.1':
            	// further upgrade

        }


        // update successful
        return true;
    }
}
