<?php
/**
 * MUSeo.
 *
 * @copyright Michael ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael ueberschaer <konakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Nov 25 13:18:41 CET 2012.
 */

/**
 * Version information implementation class.
 */
class MUSeo_Version extends MUSeo_Base_Version
{
/**
 * Version information base class.
 */
class MUSeo_Base_Version extends Zikula_AbstractVersion
{
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version'] = '1.0.0';
        // the displayed name of the module
        $meta['displayname'] = $this->__('MUSeo');
        // the module description
        $meta['description'] = $this->__('MUSeo - a module to handle SEO better.');
        //! url version of name, should be in lowercase without space
        $meta['url'] = $this->__('museo');
        // core requirement
        $meta['core_min'] = '1.3.1'; // requires minimum 1.3.1 or later
        $meta['core_max'] = '1.3.99'; // not ready for 1.4.0 yet

        // define special capabilities of this module
        $meta['capabilities'] = array(
            HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => true) /*,
             HookUtil::PROVIDER_CAPABLE => array('enabled' => true), // TODO: see #15
             'authentication' => array('version' => '1.0'),
             'profile'        => array('version' => '1.0', 'anotherkey' => 'anothervalue'),
             'message'        => array('version' => '1.0', 'anotherkey' => 'anothervalue')
             */
        );

        // permission schema
        // DEBUG: permission schema aspect starts
        $meta['securityschema'] = array(
            'MUSeo::'        => '::',

            'MUSeo:Metatag:' => 'MetatagID::',
            'MUSeo:Module:'  => 'ModuleID::'
        );
        // DEBUG: permission schema aspect ends

        return $meta;
    }
}
