<?php
/**
 * MUSeo.
 *
 * @copyright Michael ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael ueberschaer <konakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Nov 20 20:20:03 CET 2012.
 */

/**
 * Check permissions during the workflow.
 *
 * @param array $obj
 * @param int $permLevel
 * @param int $currentUser
 * @return bool
 */
function MUSeo_workflow_simpleapproval_permissioncheck($obj, $permLevel, $currentUser)
{
    /** TODO */
    $component = 'MUSeo::';
    // process $obj and calculate an instance
    /** TODO */
    $instance = '::';

    return SecurityUtil::checkPermission($component, $instance, $permLevel, $currentUser);
}
