<?php
/**
 * MUSeo.
 *
 * @copyright Michael ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael ueberschaer <konakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Nov 25 13:18:41 CET 2012.
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for module entities.
 */
class MUSeo_Entity_Validator_Module extends MUSeo_Entity_Validator_Base_Module
{
    // here you can add custom validation methods or override existing checks
}
