<?php
/**
 * MUSeo.
 *
 * @copyright Michael ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael ueberschaer <konakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Nov 20 20:20:03 CET 2012.
 */

/**
 * This is the HandleModules api helper class.
 */
class MUSeo_Api_Base_HandleModules extends Zikula_AbstractApi
{
    /**
     * get available HandleModules panel links
     *
     * @return array Array of admin links
     */
    public function getlinks()
    {
        $links = array();

        return $links;
    }
}
