<?php
/**
 * MUSeo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Utility implementation class for model helper methods.
 */
class MUSeo_Util_Model extends MUSeo_Util_Base_Model
{
    /**
     * Returns a repository for metatags.
     */
    public static function getMetatagRepository()
    {
        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository('MUSeo_Entity_Metatag');

        return $repository;
    } 

    /**
     * Returns a repository for extensions.
     */
    public static function getExtensionRepository()
    {
        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository('MUSeo_Entity_Extension');

        return $repository;
    } 
}
