<?php
/**
 * MUSeo.
 *
 * @copyright Michael ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael ueberschaer <konakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Nov 20 20:20:03 CET 2012.
 */

/**
 * Installer base class
 */
class MUSeo_Base_Installer extends Zikula_AbstractInstaller
{
    /**
     * Install the MUSeo application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        // create all tables from according entity definitions
        try {
            DoctrineHelper::createSchema($this->entityManager, $this->listEntityClasses());
        } catch (Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while creating the tables for the %s module.', array($this->getName())));
        }

        // set up all our vars with initial values
        $this->setVar('modules', 'News,Eternizer');
        $this->setVar('controllers', 'main,view,display');

        // create the default data for MUSeo
        $this->createDefaultData();

        // register persistent event handlers
        $this->registerPersistentEventHandlers();

        // register hook subscriber bundles
        HookUtil::registerSubscriberBundles($this->version->getHookSubscriberBundles());

        // initialisation successful
        return true;
    }

    /**
     * Upgrade the MUSeo application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldversion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldversion)
    {
        /*
         // Upgrade dependent on old version number
         switch ($oldversion) {
         case 1.0.0:
         // do something
         // ...
         // update the database schema
         try {
         DoctrineHelper::updateSchema($this->entityManager, $this->listEntityClasses());
         } catch (Exception $e) {
         if (System::isDevelopmentMode()) {
         LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
         }
         return LogUtil::registerError($this->__f('An error was encountered while dropping the tables for the %s module.', array($this->getName())));
         }
         }
         */

        // update successful
        return true;
    }

    /**
     * Uninstall MUSeo.
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule($this->getName());
        if ($result === false) {
            return LogUtil::registerError($this->__f('An error was encountered while removing stored object workflows for the %s module.', array($this->getName())));
        }

        try {
            DoctrineHelper::dropSchema($this->entityManager, $this->listEntityClasses());
        } catch (Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while dropping the tables for the %s module.', array($this->getName())));
        }

        // unregister persistent event handlers
        EventUtil::unregisterPersistentModuleHandlers('MUSeo');

        // unregister hook subscriber bundles
        HookUtil::unregisterSubscriberBundles($this->version->getHookSubscriberBundles());

        // remove all module vars
        $this->delVars();

        // deletion successful
        return true;
    }

    /**
     * Build array with all entity classes for MUSeo.
     *
     * @return array list of class names.
     */
    protected function listEntityClasses()
    {
        $classNames = array();
        $classNames[] = 'MUSeo_Entity_Metatag';
        $classNames[] = 'MUSeo_Entity_Module';

        return $classNames;
    }
    /**
     * Create the default data for MUSeo.
     *
     * @return void
     */
    protected function createDefaultData()
    {
        // Ensure that tables are cleared
        $this->entityManager->transactional(function ($entityManager)
        {
            $entityManager->getRepository('MUSeo_Entity_Metatag')->truncateTable();
            $entityManager->getRepository('MUSeo_Entity_Module')->truncateTable();
        }
        );

        // Insertion successful
        return true;
    }

    /**
     * Register persistent event handlers.
     * These are listeners for external events of the core and other modules.
     */
    protected function registerPersistentEventHandlers()
    {
        // core
        EventUtil::registerPersistentModuleHandler('MUSeo', 'api.method_not_found', array('MUSeo_Listener_Core', 'apiMethodNotFound'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'core.preinit', array('MUSeo_Listener_Core', 'preInit'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'core.init', array('MUSeo_Listener_Core', 'init'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'core.postinit', array('MUSeo_Listener_Core', 'postInit'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'controller.method_not_found', array('MUSeo_Listener_Core', 'controllerMethodNotFound'));

        // installer
        EventUtil::registerPersistentModuleHandler('MUSeo', 'installer.module.installed', array('MUSeo_Listener_Installer', 'moduleInstalled'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'installer.module.upgraded', array('MUSeo_Listener_Installer', 'moduleUpgraded'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'installer.module.uninstalled', array('MUSeo_Listener_Installer', 'moduleUninstalled'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'installer.subscriberarea.uninstalled', array('MUSeo_Listener_Installer', 'subscriberAreaUninstalled'));

        // modules
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module_dispatch.postloadgeneric', array('MUSeo_Listener_ModuleDispatch', 'postLoadGeneric'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module_dispatch.preexecute', array('MUSeo_Listener_ModuleDispatch', 'preExecute'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module_dispatch.postexecute', array('MUSeo_Listener_ModuleDispatch', 'postExecute'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module_dispatch.custom_classname', array('MUSeo_Listener_ModuleDispatch', 'customClassname'));

        // mailer
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.mailer.api.sendmessage', array('MUSeo_Listener_Mailer', 'sendMessage'));

        // page
        EventUtil::registerPersistentModuleHandler('MUSeo', 'pageutil.addvar_filter', array('MUSeo_Listener_Page', 'pageutilAddvarFilter'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'system.outputfilter', array('MUSeo_Listener_Page', 'systemOutputfilter'));

        // errors
        EventUtil::registerPersistentModuleHandler('MUSeo', 'setup.errorreporting', array('MUSeo_Listener_Errors', 'setupErrorReporting'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'systemerror', array('MUSeo_Listener_Errors', 'systemError'));

        // theme
        EventUtil::registerPersistentModuleHandler('MUSeo', 'theme.preinit', array('MUSeo_Listener_Theme', 'preInit'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'theme.init', array('MUSeo_Listener_Theme', 'init'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'theme.load_config', array('MUSeo_Listener_Theme', 'loadConfig'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'theme.prefetch', array('MUSeo_Listener_Theme', 'preFetch'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'theme.postfetch', array('MUSeo_Listener_Theme', 'postFetch'));

        // view
        EventUtil::registerPersistentModuleHandler('MUSeo', 'view.init', array('MUSeo_Listener_View', 'init'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'view.postfetch', array('MUSeo_Listener_View', 'postFetch'));

        // user login
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.login.started', array('MUSeo_Listener_UserLogin', 'started'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.login.veto', array('MUSeo_Listener_UserLogin', 'veto'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.login.succeeded', array('MUSeo_Listener_UserLogin', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.login.failed', array('MUSeo_Listener_UserLogin', 'failed'));

        // user logout
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.logout.succeeded', array('MUSeo_Listener_UserLogout', 'succeeded'));

        // user
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.gettheme', array('MUSeo_Listener_User', 'getTheme'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.account.create', array('MUSeo_Listener_User', 'create'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.account.update', array('MUSeo_Listener_User', 'update'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.account.delete', array('MUSeo_Listener_User', 'delete'));

        // registration
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.registration.started', array('MUSeo_Listener_UserRegistration', 'started'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.registration.succeeded', array('MUSeo_Listener_UserRegistration', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.ui.registration.failed', array('MUSeo_Listener_UserRegistration', 'failed'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.registration.create', array('MUSeo_Listener_UserRegistration', 'create'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.registration.update', array('MUSeo_Listener_UserRegistration', 'update'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'user.registration.delete', array('MUSeo_Listener_UserRegistration', 'delete'));

        // users module
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.users.config.updated', array('MUSeo_Listener_Users', 'configUpdated'));

        // group
        EventUtil::registerPersistentModuleHandler('MUSeo', 'group.create', array('MUSeo_Listener_Group', 'create'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'group.update', array('MUSeo_Listener_Group', 'update'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'group.delete', array('MUSeo_Listener_Group', 'delete'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'group.adduser', array('MUSeo_Listener_Group', 'addUser'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'group.removeuser', array('MUSeo_Listener_Group', 'removeUser'));

        // special purposes and 3rd party api support
        EventUtil::registerPersistentModuleHandler('MUSeo', 'get.pending_content', array('MUSeo_Listener_ThirdParty', 'pendingContentListener'));
        EventUtil::registerPersistentModuleHandler('MUSeo', 'module.content.gettypes', array('MUSeo_Listener_ThirdParty', 'contentGetTypes'));
    }
}
