<?php
/**
 * MUSeo.
 *
 * @copyright Michael ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUSeo
 * @author Michael ueberschaer <konakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Tue Nov 20 20:20:03 CET 2012.
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the base validation class for module entities.
 */
class MUSeo_Entity_Validator_Base_Module extends MUSeo_Validator
{

    /**
     * Performs all validation rules.
     *
     * @return mixed either array with error information or true on success
     */
    public function validateAll()
    {
        $errorInfo = array('message' => '', 'code' => 0, 'debugArray' => array());
        $dom = ZLanguage::getModuleDomain('MUSeo');
        if (!$this->isValidInteger('id')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('id'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('id', 9)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('id', 9), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('name', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('name', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('name')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('name'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('controllerForSingleObject', 50)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('controllerForSingleObject', 50), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('controllerForSingleObject')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('controllerForSingleObject'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('parameterForObjects', 50)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('parameterForObjects', 50), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('objectsOfModule', 100)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('objectsOfModule', 100), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('objectsOfModule')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('objectsOfModule'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('nameOfIdentifier', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('nameOfIdentifier', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('nameOfIdentifier')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('nameOfIdentifier'), $dom);
            return $errorInfo;
        }
        if (!$this->isUniqueValue('name')) {
            $errorInfo['message'] = __f('The name %s is already assigned. Please choose another name.', array($this->entity['name']), $dom);
            return $errorInfo;
        }
        return true;
    }

    /**
     * Check for unique values.
     *
     * This method determines if there already exist modules with the same module.
     *
     * @param string $fieldName The name of the property to be checked
     * @return boolean result of this check, true if the given module does not already exist
     */
    public function isUniqueValue($fieldName)
    {
        if (empty($this->entity[$fieldName])) {
            return false;
        }

        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository('MUSeo_Entity_Module');

        $excludeid = $this->entity['id'];
        return $repository->detectUniqueState($fieldName, $this->entity[$fieldName], $excludeid);
    }

    /**
     * Get entity.
     *
     * @return Zikula_EntityAccess
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Set entity.
     *
     * @param Zikula_EntityAccess $entity.
     *
     * @return void
     */
    public function setEntity(Zikula_EntityAccess $entity = null)
    {
        $this->entity = $entity;
    }

}
